### ISSUE TITLE
[Bug]: caiyun 获取 ssoToken 异常 return_nullishCoalesce is not defined

### ISSUE THREAD

**Issue by tillsunrise** [asunajs/asuna#45]
### 模块类型

caiyun @asunajs/caiyun 0.2.6

### 运行环境和版本

青龙面板最新

### 发生了什么

获取 ssoToken报异常，看了代码，自己试了下，应该是调用querySpecToken返回了参数错误
![image](https://github.com/asunajs/asuna/assets/71312152/2bc43e2d-9546-4617-b204-c338c2df6728)
![image](https://github.com/asunajs/asuna/assets/71312152/c812e5d6-982a-43b4-83dd-9d99ee7d678b)

**Comment by catlair** [comment]
感谢反馈，经过测试，问题确实存在。

> 看了代码，自己试了下，应该是调用querySpecToken返回了参数错误

不知道你怎么做的测试，但实际上这里与此无关。

异常是由程序本身抛出，而非接口错误。

验证得知该错误仅发生在 cjs 模式的 @asunajs/http 模块中，进一步验证为 tsup minify 后导致，由于供应链的打包工具导致该错误，暂时无法解决，可以退回之前版本。

**Comment by catlair** [comment]
check [0.2.7](https://www.npmjs.com/package/@asunajs/caiyun) !

Recommend esm over cjs

**Comment by tillsunrise** [comment]
感谢作者大大，新版本ok了
