### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Chenawsl** [asunajs/asuna#48]
### 模块类型

pushplus发送失败

### 运行环境和版本

本地win10 nodejs

### 发生了什么

[09:40:25] i pushplus发送失败: Expected values which are string, Buffer, Node.js Stream, Generator, AsyncGenerator, predicate returns truthy for any value, or undefined. Received values of type Object.

**Comment by catlair** [comment]
请提 供模块类型 该选项为必填项（而不是 pushplus发送失败），否则我无法知道你的错误发生在哪儿

**Comment by lidapao197** [comment]
我也遇到了这个问题，天翼云pushplus推送失败，消息配置如下
{
   "caiyun": [
    {
      "token": "",
      "phone": "",
      "auth": ""
    }
  ], 
  "ecloud": [
    {
      "username": "",
      "password": ""
    },
    {
      "username": "",
      "password": ""
    }
  ],
 "message": {
    "pushplus": {
      "token": ""
    },
    "onlyError": false
  }
}

**Comment by catlair** [comment]
@lidapao197 thanks !

:bug:fixed !

news :tada:

- @asunajs/caiyun@0.2.10
- @asunajs/ecloud@0.0.2
